name: generate-snake

on:
  schedule: 
    - cron: "59 23 * * *"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Gerar cobrinha
        uses: Platane/snk@v3
        with:
          github_user_name: CarolineOliveiraSilva
          outputs: dist/snake.svg

      - name: Publicar no branch output
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

