name: Generate Snake

on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Gerar a cobrinha
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: CarolineOliveiraSilva
          outputs: |
            dist/github-contribution-grid-snake.svg

          
          snake_color: "#ff66cc"       
          background: "#0d0d0d"         
          grid_color: "#ff99cc"        

      - name: Upload Snake
        uses: actions/upload-artifact@v4
        with:
          name: snake
          path: dist/github-contribution-grid-snake.svg

      - name: Deploy Snake to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
